### ISSUE TITLE
Data service API adjsutment

### ISSUE THREAD

**Issue by kazhamiakin** [smartcommunitylab/sco.trentorienta#2]
Each list method of the data service should provide the pagination support. For example,
- getEventsByTag(filterTag: string, from: number, to:number)
- getEventsBySource(filterSource: string, from: number, to:number)
- getEventsByTheme(filterTheme: string, from: number, to:number)

For the getThemeList, getSourceList, and getTagsList return a map, which contains for each theme/source/tag a number of objects associated. E.g., {cultura:5,sport:3, trasporti:2}

**Comment by luca76** [comment]
Fixed in 26e2e553aad526845f585ff785572d573ace9cbf

Code example for getThemesList():

```
import { eventType } from '../../app/struct-data';
import { occurenciesType } from '../../app/struct-data';
import { EventService } from '../../app/event-service';
[...]
export class ListPage {
  occurencies: occurenciesType[];
  [...]
    this.eventService.getThemesList()
      .then(occurencies => {
        this.occurencies = occurencies;
        this.items = [];
        for (let i = 0; i < Object.keys(this.occurencies).length; i++) {
          let key_name = Object.keys(this.occurencies)[i];
          this.items.push({
            title: key_name,
            note: this.occurencies[key_name].toString(),
            icon: this.icons[Math.floor(Math.random() * this.icons.length)]
          });
        }
      });
   [...]
```
